kind: SwitchConfig
version: v1alpha1
kubeconfigStores:
  - kind: filesystem
    showPrefix: false
    paths:
    - ~/.config/kubeconfigs/ops.yaml
  - kind: gke
    config:
      authentication:
        authenticationType: gcloud
      projectIDs:
        - mcp-hostcluster-dev
        - mcp-hostcluster-staging
        - mcp-hostcluster-prod
        - orchestration-orchestrating
        - orchestration-build
        - orchestration-ci
  - kind: eks
    id: orchestration-orchestration-us-east-1
    config:
      profile: o-o
      region: us-east-1
  - kind: eks
    id: orchestration-orchestration-us-west-2
    config:
      profile: o-o
      region: us-west-2