k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  skipLatestRevCheck: false
  ui:
    enableMouse: false
    headless: true
    logoless: true
    noIcons: false
    skin: catppuccin-frappe-transparent
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: true
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70