k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  skipLatestRevCheck: false
  ui:
    enableMouse: true
    headless: true
    logoless: true
    noIcons: false
    skin: catppuccin
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: true
    textWrap: false
    showTime: false
  currentContext: upbound_upbound_thomson-test-cp_gke_mcp-hostcluster-dev_us-central1_hc-47a42992-bd46-4524-b733-9a996de25580
  currentCluster: upbound_upbound_thomson-test-cp_gke_mcp-hostcluster-dev_us-central1_hc-47a42992-bd46-4524-b733-9a996de25580
  clusters:
    gke_mcp-hostcluster-dev_us-central1_hc-47a42992-bd46-4524-b733-9a996de25580:
      namespace:
        active: mcp-8017c7ca-220b-4fcc-baa2-4e0496fdb21c-system
        lockFavorites: false
        favorites:
        - istio-system
        - mcp-8017c7ca-220b-4fcc-baa2-4e0496fdb21c-system
        - mcp-59279fe3-de2d-498f-96ca-6202207250f3-system
        - all
        - default
      view:
        active: deployments
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    gke_upbound-cloud-dev_us-west1_primary-dev-us-west1:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: hostcluster
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    kind-local-dev:
      namespace:
        active: mcp-f0ef6b7b-ab6d-4f13-a896-ea91228d49d4-system
        lockFavorites: false
        favorites:
        - mcp-f0ef6b7b-ab6d-4f13-a896-ea91228d49d4-system
        - upbound-system
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    upbound_upbound_thomson-test-cp_gke_mcp-hostcluster-dev_us-central1_hc-47a42992-bd46-4524-b733-9a996de25580:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/9k/qqc6dy317qx4h6rgjxtwgdl40000gn/T/k9s-screens-nicholasthomson
